live_config_reload = true

[env]
TERM = "alacritty"

[font]
size = 17

[font.bold]
family = "Source Code Pro"

[font.bold_italic]
family = "Source Code Pro"

[font.italic]
family = "Source Code Pro"

[font.normal]
family = "Source Code Pro"

[window]
opacity = 0.5

[window.padding]
decoration = "none"
dynamic_padding = true
x = 10
y = 10
